### ISSUE TITLE
Problemy z trybem specjalnym

### ISSUE THREAD

**Issue by kretonpodziemny** [Dove6/Re-SP#3]
Niestety w niektórych przypadkach ddraw nie chroni zremasterowanej wersji RiSP przed uruchomieniem trybu specjalnego. Jeżeli podczas filmiku albo jakiegoś dłuższego przejścia między zadaniami zmienimy kartę, filmik/animacja będą dalej leciały a po ich zakończeniu włączy się tryb specjalny, który czasem sam się kończy po przejściu do jakiejś lokacji (np. do chatki Kretesa).

**Comment by Dove6** [comment]
Naprawa takich błędów nie wchodzi w zakres tego projektu.

Ale polecam przetestować z https://github.com/FunkyFr3sh/cnc-ddraw

**Comment by kretonpodziemny** [comment]
Szkoda, bo Re:SP byłby dobrą okazją do likwidacji przyczyny rozsmarowywania (jak w RiKwA).   No, ale ok. Z cncddraw błędu nie udało mi się wywołać (pytanie czy na nowym komputerze w ogóle by mi się udało).  
     
      
       
        Dnia 15 maja 2024 20:13 Dawid Sygocki ***@***.***&gt; napisał(a):
       
    
       
         
 Naprawa takich błędów nie wchodzi w zakres tego projektu. 
 Ale polecam przetestować z  github.com https://github.com/FunkyFr3sh/cnc-ddraw
